import type { Metadata } from 'next';
import { PageFrame, PageHeader, SectionTitle } from '../../components/PagePrimitives';

export const metadata: Metadata = { title: 'Efficiency', description: 'Cache-first, delta-aware, smallest-capable-team execution.' };
const flow = ['CACHE', 'RETRIEVE', 'DELTA', 'TRIAGE', 'SMALLEST TEAM', 'EXECUTE', 'VERIFY', 'LEARN', 'REUSE'];

export default function EfficiencyPage() {
  return <><PageHeader eyebrow="Efficiency / measured, not imagined" title="Spend context where it changes the answer." intro="The architecture starts with retrieval and a compact delta. It escalates to a specialist only when the task earns one." /><PageFrame><div className="grid-paper overflow-x-auto border border-black/15 p-5 sm:p-8"><div className="flex min-w-[760px] items-center gap-2">{flow.map((item, index) => <div className="flex flex-1 items-center gap-2" key={item}><div className="flex min-h-24 flex-1 items-center justify-center border border-black/25 bg-[var(--paper)] p-3 text-center font-mono text-xs font-bold tracking-[0.08em]">{item}</div>{index < flow.length - 1 ? <span aria-hidden="true" className="text-[var(--signal)]">→</span> : null}</div>)}</div></div><div className="mt-16 grid gap-8 lg:grid-cols-3"><Metric title="Cache first" text="Retrieve a fresh, scoped, verified artifact before repeating reasoning." /><Metric title="Delta next" text="Pass a stable reference and the changed facts instead of full history." /><Metric title="Team last" text="Start with one owner; fan out only for independent bounded work." /></div><div className="mt-16 grid gap-8 lg:grid-cols-2"><div><SectionTitle>Illustrative comparison</SectionTitle><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="border border-black/20 p-5"><p className="eyebrow text-[var(--signal)]">Naive</p><ul className="mt-5 space-y-3 text-sm"><li>Full context</li><li>Duplicate research</li><li>Many bots</li><li>Repeat planning</li><li>Large fan-out</li></ul></div><div className="mint-panel p-5"><p className="eyebrow">GrokBot Office</p><ul className="mt-5 space-y-3 text-sm"><li>Cache</li><li>Delta</li><li>Known workflow</li><li>Smallest team</li><li>Verification + learning</li></ul></div></div></div><div className="dark-panel p-6"><p className="eyebrow text-[var(--mint)]">No fabricated savings</p><p className="mt-5 text-xl leading-8">This site uses relative units only. Token, latency, and cost claims appear only when a real benchmark with a stated methodology exists.</p></div></div></PageFrame></>;
}

function Metric({ title, text }: { title: string; text: string }) { return <article className="border-t-2 border-[var(--signal)] pt-4"><h2 className="font-display text-3xl uppercase">{title}</h2><p className="mt-3 leading-7 text-black/65">{text}</p></article>; }
