import type { Metadata } from 'next';
import Link from 'next/link';
import { PageFrame, PageHeader, SectionTitle } from '../../components/PagePrimitives';

export const metadata: Metadata = { title: 'Security', description: 'Security boundaries for the GrokBot Office workforce model.' };

export default function SecurityPage() {
  return <><PageHeader eyebrow="Security / identity is not isolation" title="BOT IDENTITY ≠ SECURITY BOUNDARY." intro="Real isolation uses accounts, credentials, permissions, scopes, sandboxes, approval gates, and infrastructure." /><PageFrame><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div className="dark-panel p-7"><p className="eyebrow text-[var(--mint)]">Treat as untrusted</p><ul className="mt-6 space-y-4 text-lg"><li>Third-party MCP servers</li><li>Skills and repositories</li><li>External workers</li><li>Generated artifacts</li><li>Shared prompts and packets</li></ul></div><div><SectionTitle>Minimum release boundary</SectionTitle><ol className="mt-6 space-y-5 text-lg leading-8"><li><strong>1.</strong> Keep credentials out of role metadata, examples, logs, traces, and backups.</li><li><strong>2.</strong> Use separate accounts and scopes for external workers.</li><li><strong>3.</strong> Require explicit approval for consequential actions.</li><li><strong>4.</strong> Redact before persistence, not just display.</li><li><strong>5.</strong> Revoke and review after an incident.</li></ol></div></div><div className="mt-16 mint-panel p-7"><p className="eyebrow">Public packaging</p><p className="mt-4 max-w-3xl text-xl leading-8">The public repositories exclude harvest exports, account state, autonomy reports, browser/session data, cookies, tokens, keys, credentials, generated archives, and machine-specific paths.</p><div className="mt-6 flex flex-wrap gap-5 font-mono text-xs uppercase tracking-[0.12em]"><Link className="underline underline-offset-4" href="/docs#security">Read the documentation boundary →</Link><a className="underline underline-offset-4" href="https://github.com/M4G3LL4N0/grokbot-office/blob/main/SECURITY.md" rel="noreferrer" target="_blank">Runtime security policy →</a><a className="underline underline-offset-4" href="https://github.com/M4G3LL4N0/grokbot-office-website/blob/main/SECURITY.md" rel="noreferrer" target="_blank">Website security policy →</a></div></div></PageFrame></>;
}
